"""create document tables

Revision ID: 2ad50f59402a
Revises: ec5b9c573262
Create Date: 2026-09-17 00:22:05.885851

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2ad50f59402a'
down_revision: Union[str, Sequence[str], None] = 'ec5b9c573262'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('collections',
    sa.Column('name', sa.String(length=255), nullable=False, comment='Collection display name'),
    sa.Column('description', sa.Text(), nullable=True, comment='Optional description of this collection'),
    sa.Column('tenant_id', sa.Uuid(), nullable=False, comment='The tenant this collection belongs to'),
    sa.Column('created_by', sa.Uuid(), nullable=True, comment='The user who created this collection'),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False, comment='False = soft-deleted'),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_collections_tenant_id'), 'collections', ['tenant_id'], unique=False)
    op.create_table('documents',
    sa.Column('title', sa.String(length=500), nullable=False, comment='User-facing document title'),
    sa.Column('filename', sa.String(length=500), nullable=False, comment='Original uploaded filename'),
    sa.Column('description', sa.Text(), nullable=True, comment='Optional document description'),
    sa.Column('mime_type', sa.String(length=255), nullable=False, comment='MIME type (e.g., application/pdf)'),
    sa.Column('file_size', sa.BigInteger(), nullable=False, comment='File size in bytes'),
    sa.Column('storage_key', sa.String(length=1000), nullable=False, comment='Key/path in storage backend'),
    sa.Column('checksum', sa.String(length=64), nullable=False, comment='SHA-256 hash of file content'),
    sa.Column('current_version', sa.Integer(), nullable=False, comment='Current (latest) version number'),
    sa.Column('status', sa.Enum('uploaded', 'processing', 'ready', 'error', 'archived', name='document_status', create_constraint=True), server_default='uploaded', nullable=False, comment='Processing status (uploaded → processing → ready)'),
    sa.Column('tenant_id', sa.Uuid(), nullable=False, comment='The tenant this document belongs to'),
    sa.Column('uploaded_by', sa.Uuid(), nullable=True, comment='The user who uploaded this document'),
    sa.Column('collection_id', sa.Uuid(), nullable=True, comment='Optional collection this document belongs to'),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False, comment='False = soft-deleted (hidden but preserved)'),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['collection_id'], ['collections.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['uploaded_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_documents_collection_id'), 'documents', ['collection_id'], unique=False)
    op.create_index(op.f('ix_documents_tenant_id'), 'documents', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_documents_uploaded_by'), 'documents', ['uploaded_by'], unique=False)
    op.create_table('document_versions',
    sa.Column('document_id', sa.Uuid(), nullable=False, comment='The document this version belongs to'),
    sa.Column('version_number', sa.Integer(), nullable=False, comment='Sequential version number (1, 2, 3, ...)'),
    sa.Column('storage_key', sa.String(length=1000), nullable=False, comment="Storage key for this version's file"),
    sa.Column('file_size', sa.BigInteger(), nullable=False, comment="Size of this version's file in bytes"),
    sa.Column('mime_type', sa.String(length=255), nullable=False, comment='MIME type of this version'),
    sa.Column('checksum', sa.String(length=64), nullable=False, comment="SHA-256 hash of this version's content"),
    sa.Column('uploaded_by', sa.Uuid(), nullable=True, comment='Who uploaded this version'),
    sa.Column('change_note', sa.Text(), nullable=True, comment='Optional note describing changes in this version'),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['uploaded_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_document_versions_document_id'), 'document_versions', ['document_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_document_versions_document_id'), table_name='document_versions')
    op.drop_table('document_versions')
    op.drop_index(op.f('ix_documents_uploaded_by'), table_name='documents')
    op.drop_index(op.f('ix_documents_tenant_id'), table_name='documents')
    op.drop_index(op.f('ix_documents_collection_id'), table_name='documents')
    op.drop_table('documents')
    op.drop_index(op.f('ix_collections_tenant_id'), table_name='collections')
    op.drop_table('collections')
    # ### end Alembic commands ###
