"""create_document_chunks_table

Revision ID: 5efb7419016e
Revises: 2ad50f59402a
Create Date: 2026-09-23 11:45:41.735693

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5efb7419016e'
down_revision: Union[str, Sequence[str], None] = '2ad50f59402a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('document_chunks',
    sa.Column('document_id', sa.Uuid(), nullable=False, comment='Source document'),
    sa.Column('tenant_id', sa.Uuid(), nullable=False, comment='Tenant for row-level security'),
    sa.Column('chunk_index', sa.Integer(), nullable=False, comment='Position in document (0-indexed)'),
    sa.Column('content', sa.Text(), nullable=False, comment='The actual chunk text'),
    sa.Column('token_count', sa.Integer(), nullable=False, comment='Number of tokens in this chunk'),
    sa.Column('page_number', sa.Integer(), nullable=True, comment='Page number (for PDFs)'),
    sa.Column('section_heading', sa.String(length=500), nullable=True, comment='Section heading this chunk belongs to'),
    sa.Column('version', sa.Integer(), nullable=False, comment='Document version this chunk was created from'),
    sa.Column('checksum', sa.String(length=64), nullable=False, comment='SHA-256 of chunk content (for dedup/cache)'),
    sa.Column('doc_metadata', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False, comment='Format-specific metadata'),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_document_chunks_document_id'), 'document_chunks', ['document_id'], unique=False)
    op.create_index(op.f('ix_document_chunks_tenant_id'), 'document_chunks', ['tenant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_document_chunks_tenant_id'), table_name='document_chunks')
    op.drop_index(op.f('ix_document_chunks_document_id'), table_name='document_chunks')
    op.drop_table('document_chunks')
    # ### end Alembic commands ###
