"""initial schema

Revision ID: ec5b9c573262
Revises: 
Create Date: 2026-09-07 14:55:02.531993

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ec5b9c573262'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tenants',
    sa.Column('name', sa.String(length=255), nullable=False, comment='Display name of the Organization'),
    sa.Column('slug', sa.String(length=255), nullable=False, comment="URL-friendly identifier (e.g., 'acme-corp')"),
    sa.Column('description', sa.Text(), nullable=True, comment='Brief description of the Organization'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='Indicates if the Organization is active'),
    sa.Column('settings', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False, comment='Per-tenant configuration (LLM model, limits, etc.)'),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tenants_slug'), 'tenants', ['slug'], unique=True)
    op.create_table('users',
    sa.Column('email', sa.String(length=255), nullable=False, comment="User's email address (used for login)"),
    sa.Column('hashed_password', sa.String(length=255), nullable=False, comment='Hashed password for authentication'),
    sa.Column('full_name', sa.String(length=255), nullable=False, comment="User's full name"),
    sa.Column('tenant_id', sa.Uuid(), nullable=False, comment='Foreign key to the Tenant the user belongs to'),
    sa.Column('role', sa.Enum('viewer', 'editor', 'admin', name='user_role'), server_default='viewer', nullable=False, comment='Role of the user (viewer, editor, admin)'),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False, comment='Indicates if the user account is active'),
    sa.Column('last_login', sa.DateTime(timezone=True), nullable=True, comment="Timestamp of the user's last login"),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_tenant_id'), 'users', ['tenant_id'], unique=False)
    op.create_table('refresh_tokens',
    sa.Column('token_hash', sa.String(length=255), nullable=False, comment='SHA-256 hash of the refresh token'),
    sa.Column('user_id', sa.Uuid(), nullable=False, comment='The user this token belongs to'),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False, comment='When this token expires'),
    sa.Column('is_revoked', sa.Boolean(), server_default='false', nullable=False, comment='Whether this token has been manually revoked'),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True, comment='When this token was revoked'),
    sa.Column('replaced_by_id', sa.Uuid(), nullable=True, comment='ID of the token that replaced this one (rotation chain)'),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['replaced_by_id'], ['refresh_tokens.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_refresh_tokens_token_hash'), 'refresh_tokens', ['token_hash'], unique=True)
    op.create_index(op.f('ix_refresh_tokens_user_id'), 'refresh_tokens', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_refresh_tokens_user_id'), table_name='refresh_tokens')
    op.drop_index(op.f('ix_refresh_tokens_token_hash'), table_name='refresh_tokens')
    op.drop_table('refresh_tokens')
    op.drop_index(op.f('ix_users_tenant_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_tenants_slug'), table_name='tenants')
    op.drop_table('tenants')
    # ### end Alembic commands ###
